name: Checking workflow calling

on:
  workflow_call:
    secrets:
      PAT_FOR_WORKFLOWS:
        required: true

jobs:
  triage:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v3
        with:
          repo-token: ${{ secrets.PAT_FOR_WORKFLOWS }}
      - name: Run some commands
        run: echo "This is a subworkflow"

