name: Checking workflow calling

on:
  workflow_call:

jobs:
  echo:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v3
      - name: Run some commands
        run: echo "This is a subworkflow"

