name: Cleaning up namespace

on:
  workflow_call:
    inputs:
      pr_number:
        required: true
        type: string
        description: 'Pull Request Number'
  pull_request:
    types: [opened, synchronize]

    
    #   SourceCodeBranch:
    #     required: true
    #     type: string
    # secrets:
    #     CLIENT_ID:
    #       required: true
    #     CLIENT_SECRET:
    #       required: true
    #     TENANT_ID:
    #       required: true

jobs:
  check-pr-status:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
      - name: Check Pull Request Status
        run: |
          PR_NUMBER="${{ inputs.pr_number }}"
          PR_DATA=$(curl -L \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            https://api.github.com/repos/${{ github.repository }}/pulls/$PR_NUMBER)
          PR_MERGED=$(echo "$PR_DATA" | jq -r '.merged')
          
          if [ "$PR_MERGED" == "true" ]; then
            echo "Pull Request is merged."
          else
            echo "Pull Request is not merged."
          fi

          PR_URL="${{ github.event.pull_request.html_url }}"
          echo "Pull Request URL: $PR_URL"

          # Access the pull request number
          PR_NUMBER="${{ github.event.pull_request.number }}"
          echo "Pull Request Number: $PR_NUMBER"
        
        env:
          GITHUB_TOKEN: ${{ secrets.GIT_TOKEN }}

  # cleaning-namespace:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Delete AKS Namespace
  #       if: steps.check-pr-status.outputs.merged == 'true'
  #       run: |
  #         AKS_NAMESPACE_NAME=$(echo ${{inputs.SourceCodeBranch}} | sed "s|/|-|g")
  #         echo "Namespace: ${finalBranchName}"
          
  #         # Log in to Azure if not already authenticated (skip if already done in main workflow).
  #         # az login --service-principal -u <service-principal-id> -p <service-principal-secret> --tenant <azure-tenant-id>
          
  #         # az aks namespace delete --name $AKS_NAMESPACE_NAME --resource-group rg-ais-payment-gateway --cluster-name sbpocaks --yes
      
  #       # env:
  #       #   AKS_NAMESPACE_NAME: ${{ steps.check-pr-status.outputs.namespace_name }}
        

    
