name: Cleaning up namespace

on:
  workflow_call:

jobs:
  check-pr-status:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Check Pull Request Status
        id: check-pr-status
        run: |
          # Make a GitHub API request to fetch the pull request details
          PR_DATA=$(curl -L \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            https://api.github.com/repos/${{ github.repository }}/pulls/$PR_NUMBER)
          
          # Check if the pull request is merged
          PR_MERGED=$(echo "$PR_DATA" | jq -r '.merged')

          echo "::set-output name=merged::$PR_MERGED"
        
        env:
          GITHUB_TOKEN: ${{ secrets.GIT_TOKEN }}

  # cleaning_up:
  #   runs-on: ubuntu-latest
  #   steps:

  #     - name: Delete AKS Namespace
  #       if: steps.check-pr-status.outputs.merged == 'true'
  #       run: |
  #         AKS_NAMESPACE_NAME="my-aks-namespace"  # Replace with your AKS namespace name or fetch it dynamically.
          
  #         # Log in to Azure if not already authenticated (skip if already done in main workflow).
  #         # az login --service-principal -u <service-principal-id> -p <service-principal-secret> --tenant <azure-tenant-id>
          
  #         az aks namespace delete --name $AKS_NAMESPACE_NAME --resource-group <resource-group-name> --cluster-name <aks-cluster-name> --yes
          
  #       env:
  #         AKS_NAMESPACE_NAME: ${{ steps.check-pr-status.outputs.namespace_name }}

    
